/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calibration;

import calibration.ui.JavaFxApp;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("Started with args: {}", (Object) args);
        JavaFxApp.main(args);
    }
}
