/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calibration;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Disabled;

@Disabled("Nothing to test")
class AppTest {

}
